build back in

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -46,24 +46,23 @@ export PATH
 
 cd $build
 
-echo "SKIPPING ACTUAL BUILD"
 
-# if [ ! -e "rebar" ]; then
-#   echo "-----> Installing Rebar from buildpack"
-#   cp ${bpdir}/opt/rebar ./
-# fi
-# 
-# echo "-----> Building with Rebar"
-# unset GIT_DIR
-# ./rebar get-deps compile 2>&1 | sed -u 's/^/       /'
-# if [ ${PIPESTATUS[0]} -ne 0 ]; then
-#   echo "-----> Build failed"
-#   exit 1
-# fi
-# 
-# if [ -f ${bpdir}/opt/otp.sh ]; then
-#   mkdir -p ${PROFILE}
-#   cp ${bpdir}/opt/otp.sh ${PROFILE}
-# fi
+if [ ! -e "rebar" ]; then
+  echo "-----> Installing Rebar from buildpack"
+  cp ${bpdir}/opt/rebar ./
+fi
+
+echo "-----> Building with Rebar"
+unset GIT_DIR
+./rebar get-deps compile 2>&1 | sed -u 's/^/       /'
+if [ ${PIPESTATUS[0]} -ne 0 ]; then
+  echo "-----> Build failed"
+  exit 1
+fi
+
+if [ -f ${bpdir}/opt/otp.sh ]; then
+  mkdir -p ${PROFILE}
+  cp ${bpdir}/opt/otp.sh ${PROFILE}
+fi
 
 echo "-----> Build succeeded"
